# Generated by Django 5.2.17 on 2026-09-14 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('compare', 'Compare'), ('workflow', 'Workflow'), ('other', 'Other')], default='compare', max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI request logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('goal', models.CharField(blank=True, help_text='What this prompt should produce', max_length=240)),
                ('category', models.CharField(choices=[('coding', 'Coding'), ('programming', 'Programming'), ('students', 'Students'), ('education', 'Education'), ('resume', 'Resume'), ('interview', 'Interview'), ('business', 'Business'), ('marketing', 'Marketing'), ('content_writing', 'Content Writing'), ('research', 'Research'), ('data_analysis', 'Data Analysis'), ('cybersecurity', 'Cybersecurity'), ('ai', 'AI'), ('productivity', 'Productivity'), ('image_generation', 'Image Generation'), ('video_generation', 'Video Generation'), ('social_media', 'Social Media'), ('freelancing', 'Freelancing'), ('other', 'Other')], default='other', max_length=30)),
                ('tags', models.CharField(blank=True, help_text='Comma separated', max_length=240)),
                ('target_model', models.CharField(blank=True, default='any', max_length=60)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('tone', models.CharField(blank=True, choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual'), ('academic', 'Academic'), ('persuasive', 'Persuasive'), ('neutral', 'Neutral'), ('humorous', 'Humorous'), ('', 'Not set')], max_length=20)),
                ('language', models.CharField(blank=True, default='English', max_length=40)),
                ('source', models.CharField(choices=[('studio', 'Studio'), ('optimizer', 'Optimizer'), ('library', 'Library'), ('workflow', 'Workflow'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('coding', 'Coding'), ('programming', 'Programming'), ('students', 'Students'), ('education', 'Education'), ('resume', 'Resume'), ('interview', 'Interview'), ('business', 'Business'), ('marketing', 'Marketing'), ('content_writing', 'Content Writing'), ('research', 'Research'), ('data_analysis', 'Data Analysis'), ('cybersecurity', 'Cybersecurity'), ('ai', 'AI'), ('productivity', 'Productivity'), ('image_generation', 'Image Generation'), ('video_generation', 'Video Generation'), ('social_media', 'Social Media'), ('freelancing', 'Freelancing'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField()),
                ('technique', models.CharField(blank=True, max_length=60)),
                ('tags', models.CharField(blank=True, max_length=240)),
                ('featured', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('preset', models.CharField(max_length=40)),
                ('input_text', models.TextField()),
                ('final_text', models.TextField(blank=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('used_ai', models.BooleanField(default=False)),
                ('steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('score', models.FloatField(default=0)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='promptlab.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('body', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('change_note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='promptlab.prompt')),
            ],
            options={
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('prompt', 'version_number'), name='uniq_prompt_version')],
            },
        ),
    ]
