# Generated by Django 5.2.17 on 2026-09-26 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptlab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=160, unique=True)),
                ('window', models.BigIntegerField(db_index=True, default=0, help_text='Unix minute of the current window')),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rate limit bucket',
                'verbose_name_plural': 'rate limit buckets',
            },
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Signed-in owner. NULL = shared local workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Signed-in owner. NULL = shared local workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='promptanalysis',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Signed-in owner. NULL = shared local workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Signed-in owner. NULL = shared local workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
