# Generated by Django 5.2.17 on 2026-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('tshirt', 'T-Shirt'), ('pant', 'Pant'), ('jeans', 'Jeans'), ('shorts', 'Shorts'), ('jacket', 'Jacket'), ('hoodie', 'Hoodie'), ('sweater', 'Sweater'), ('dress', 'Dress'), ('skirt', 'Skirt'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('other', 'Other')], default='other', max_length=30)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('pattern', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('formality', models.CharField(choices=[('formal', 'Formal'), ('smart_casual', 'Smart Casual'), ('casual', 'Casual'), ('sport', 'Sport')], default='casual', max_length=30)),
                ('season', models.CharField(blank=True, default='all', max_length=80)),
                ('occasions', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe/')),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('worn', 'Worn'), ('laundry', 'In Laundry'), ('unavailable', 'Unavailable')], default='clean', max_length=20)),
                ('wear_count', models.PositiveIntegerField(default=0)),
                ('last_worn', models.DateTimeField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('ai_tagged', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
