# Generated by Django 5.2.17 on 2026-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_item_color_family_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='palette',
            field=models.JSONField(blank=True, default=list, help_text='Dominant colours extracted from the photo: [{hex,name,family,share}]'),
        ),
    ]
