# Generated by Django 5.2.17 on 2026-09-26 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_outfit_owner'),
        ('wardrobe', '0005_item_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'feedback'},
        ),
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ['-favorite', '-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='outfit',
            name='last_worn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='notes',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='outfit',
            name='wear_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_set', to='outfits.outfit'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='wardrobe.item'),
        ),
    ]
