# Generated by Django 5.2.17 on 2026-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occasion', models.CharField(default='casual', max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
